appId: com.docash
---
- launchApp:
    clearState: true
- extendedWaitUntil:
    visible: 'Balance total'
    timeout: 60000
- tapOn: 'Open options'
- assertVisible: 'Options'
- tapOn: 'Español'
- assertVisible: 'Opciones'
- assertVisible: 'Apariencia'
