import { StyleSheet } from 'react-native';
import { radius, spacing, type, type Palette } from '../theme';

export const makeStyles = (c: Palette) =>
  StyleSheet.create({
    root: { flex: 1, backgroundColor: c.paper },
    center: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: c.paper },
    homeContent: { paddingHorizontal: spacing.xl, paddingBottom: spacing.xl + 72 },
    page: { flex: 1, backgroundColor: c.paper },
    screenTransition: { flex: 1 },
    monthLabel: { color: c.ink, fontSize: 30, fontWeight: '800', marginTop: spacing.lg, marginBottom: spacing.sm },
    balanceCard: { backgroundColor: c.primary, borderRadius: 22, paddingHorizontal: spacing.xl, paddingVertical: spacing.lg, marginTop: spacing.md },
    summaryRow: { flexDirection: 'row', gap: spacing.md, marginTop: spacing.md },
    summaryCard: { flex: 1, minHeight: 92, borderRadius: 18, padding: spacing.lg, flexDirection: 'row', alignItems: 'center', gap: spacing.md },
    incomeCard: { backgroundColor: c.incomeSoft },
    expenseCard: { backgroundColor: c.faint },
    summaryIconIncome: { width: 48, height: 48, borderRadius: 24, backgroundColor: '#D8F6EC', alignItems: 'center', justifyContent: 'center' },
    summaryIconExpense: { width: 48, height: 48, borderRadius: 24, backgroundColor: '#E8EDF3', alignItems: 'center', justifyContent: 'center' },
    summaryLabel: { color: c.muted, fontSize: type.bodySize, fontWeight: '700' },
    summaryAmount: { fontSize: 25, fontWeight: '800', marginTop: spacing.xs },
    incomeAmount: { color: c.income },
    expenseAmount: { color: c.ink },
    planPrompt: { backgroundColor: c.primarySoft, borderRadius: 20, padding: spacing.lg, marginTop: spacing.lg, flexDirection: 'row', gap: spacing.lg },
    planIcon: { width: 64, height: 64, borderRadius: 32, backgroundColor: '#DCEEFF', alignItems: 'center', justifyContent: 'center', marginTop: spacing.sm },
    planCopy: { flex: 1 },
    cardTitle: { color: c.ink, fontSize: 22, lineHeight: 28, fontWeight: '800' },
    helperText: { color: c.muted, fontSize: type.bodySize, lineHeight: 22, marginTop: spacing.xs },
    primaryButton: { backgroundColor: c.primary, borderRadius: radius.action, minHeight: 42, alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.lg, marginTop: spacing.md },
    primaryButtonText: { color: '#FFFFFF', fontSize: type.metaSize, fontWeight: '700' },
    budgetButton: { borderWidth: 2, borderColor: c.primary, borderRadius: radius.action, minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.lg, marginTop: spacing.md },
    budgetButtonText: { color: c.primary, fontSize: type.actionSize, fontWeight: '700' },
    secondaryButton: { backgroundColor: c.primarySoft, borderRadius: radius.action, minHeight: 42, alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.lg, marginTop: spacing.sm },
    secondaryButtonText: { color: c.ink, fontSize: type.metaSize, fontWeight: '700' },
    sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.xl, marginBottom: spacing.sm },
    sectionTitle: { color: c.ink, fontSize: 26, fontWeight: '800' },
    viewAllButton: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
    viewAllText: { color: c.primary, fontSize: type.bodySize, fontWeight: '700' },
    searchInput: { marginHorizontal: spacing.xl, marginTop: spacing.md, minHeight: 48, paddingHorizontal: spacing.lg, backgroundColor: c.faint, borderWidth: 1, borderColor: c.border, borderRadius: radius.action, color: c.ink, fontSize: type.metaSize },
    filterRow: { flexDirection: 'row', gap: spacing.sm, backgroundColor: c.primarySoft, borderRadius: radius.action, marginHorizontal: spacing.xl, padding: spacing.xs, marginTop: spacing.md },
    filterChip: { flex: 1, minHeight: 34, justifyContent: 'center', alignItems: 'center', borderRadius: radius.action },
    filterChipActive: { backgroundColor: c.primary },
    filterText: { color: c.ink, fontSize: type.metaSize },
    filterTextActive: { color: '#FFFFFF', fontWeight: '700' },
    movementList: { paddingHorizontal: spacing.xl, paddingTop: spacing.md, paddingBottom: spacing.xl },
    emptyText: { color: c.muted, textAlign: 'center', paddingVertical: spacing.xl },
    bottomTabs: { flexDirection: 'row', backgroundColor: c.paper, borderTopWidth: 1, borderTopColor: c.border, paddingHorizontal: spacing.sm, paddingTop: spacing.sm, paddingBottom: spacing.md, gap: spacing.xs },
    tabButton: { flex: 1, alignItems: 'center', justifyContent: 'center', minHeight: 68, borderRadius: radius.action, gap: spacing.xs },
    tabButtonActive: { backgroundColor: c.primarySoft },
    tabLabel: { color: c.muted, fontSize: type.metaSize, fontWeight: '600' },
    tabLabelActive: { color: c.primary, fontWeight: '800' },
  });
