import { StyleSheet } from 'react-native';
import { radius, spacing, type, type Palette } from '../../theme';

export const makeStyles = (c: Palette) =>
  StyleSheet.create({
    amount: {
      textAlign: 'center',
      color: c.ink,
      fontSize: 42,
      fontWeight: '800',
      marginTop: spacing.sm,
    },
    kindSegment: { flexDirection: 'row', marginHorizontal: 24, padding: spacing.xs, borderRadius: radius.action, backgroundColor: c.primarySoft },
    kindOption: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', borderRadius: radius.action },
    kindOptionText: { fontSize: 18, fontWeight: '700' },
    kindOptionExpense: { backgroundColor: c.expense },
    kindOptionIncome: { backgroundColor: c.income },
    kindOptionSelectedText: { color: c.onAction },
    amountPanel: { marginHorizontal: 24, marginTop: 20, paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
    amountLabel: { color: c.muted, fontSize: 16, fontWeight: '500' },
    amountInput: { minWidth: 180, minHeight: 64, padding: 0, color: c.ink, fontSize: 42, fontWeight: '800' },
    stepHint: {
      textAlign: 'center',
      color: c.muted,
      fontSize: type.metaSize,
      marginBottom: spacing.lg,
      marginTop: 28,
    },
    noteInput: {
      marginHorizontal: 24,
      marginTop: spacing.sm,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: radius.action,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md,
      color: c.ink,
      minHeight: 60,
      fontSize: 18,
      textAlignVertical: 'center',
    },
    divider: { height: 1, backgroundColor: c.border, marginVertical: spacing.md },
    repeatLabel: { fontSize: 18, color: c.ink },
    dateRow: { flexDirection: 'row', gap: spacing.md, marginHorizontal: 24, marginTop: 20 },
    dateControl: { flex: 1, minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingHorizontal: spacing.lg, backgroundColor: c.faint, borderRadius: radius.action },
    dateLabel: { color: c.muted, fontSize: type.bodySize, fontWeight: '800', textTransform: 'uppercase' },
    dateValue: { color: c.ink, fontSize: 18, fontWeight: '700', marginTop: spacing.xs },
    fieldLabel: {
      marginHorizontal: 24,
      marginBottom: spacing.sm,
      color: c.muted,
      fontSize: 16,
      fontWeight: '700',
      textTransform: 'uppercase',
    },
    categorySelect: {
      minHeight: 66,
      marginHorizontal: 24,
      paddingHorizontal: spacing.lg,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: radius.action,
      backgroundColor: c.faint,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
    },
    categorySelectText: { flex: 1, color: c.ink, fontSize: 18, fontWeight: '600' },
    placeholder: { color: c.muted, fontWeight: '400' },
    repeatRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginHorizontal: 24, marginTop: spacing.lg, paddingVertical: spacing.md },
    repeatCopy: { flex: 1 },
    repeatValue: { color: c.muted, fontSize: type.metaSize, marginTop: spacing.xs },
    numpadBlock: { marginTop: spacing.lg },
    submitButton: {
      marginHorizontal: 24,
      marginTop: spacing.lg,
      minHeight: 60,
      borderRadius: radius.action,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.primary,
    },
    submitButtonDisabled: { opacity: 0.45 },
    submitText: { color: '#FFFFFF', fontSize: 18, fontWeight: type.actionWeight },
    deleteButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.sm,
      marginHorizontal: spacing.xl,
      marginTop: spacing.md,
      paddingVertical: spacing.lg,
      borderRadius: radius.action,
      backgroundColor: c.faint,
      minHeight: 48,
    },
    deleteText: { color: c.expense, fontWeight: '700', fontSize: type.bodySize },
  });
