import { StyleSheet } from 'react-native';
import { radius, spacing, type, type Palette } from '../../theme';

export const makeStyles = (c: Palette) =>
  StyleSheet.create({
    amount: {
      textAlign: 'center',
      fontSize: 40,
      fontWeight: '800',
      marginTop: spacing.md,
      marginBottom: spacing.lg,
    },
    stepHint: {
      textAlign: 'center',
      color: c.muted,
      fontSize: type.metaSize,
      marginBottom: spacing.md,
    },
    noteInput: {
      marginHorizontal: spacing.xl,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: radius.action,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md,
      color: c.ink,
      minHeight: 44,
    },
    divider: { height: 1, backgroundColor: c.border, marginVertical: spacing.md },
    repeatRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginHorizontal: spacing.xl,
      marginTop: spacing.md,
      minHeight: 40,
    },
    repeatLabel: { fontSize: type.bodySize, color: c.ink },
    fieldLabel: {
      marginHorizontal: spacing.xl,
      marginBottom: spacing.sm,
      color: c.muted,
      fontSize: type.metaSize,
      fontWeight: '700',
      textTransform: 'uppercase',
    },
    categorySelect: {
      minHeight: 54,
      marginHorizontal: spacing.xl,
      paddingHorizontal: spacing.lg,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: radius.action,
      backgroundColor: c.faint,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
    },
    categorySelectText: { flex: 1, color: c.ink, fontSize: type.bodySize, fontWeight: '600' },
    placeholder: { color: c.muted, fontWeight: '400' },
    chevron: { fontSize: 24, lineHeight: 20, marginTop: -5 },
    submitButton: {
      marginHorizontal: spacing.xl,
      marginTop: spacing.lg,
      minHeight: 50,
      borderRadius: radius.action,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.primary,
    },
    submitButtonDisabled: { opacity: 0.45 },
    submitText: { color: c.onAction, fontSize: type.actionSize, fontWeight: type.actionWeight },
    deleteButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.sm,
      marginHorizontal: spacing.xl,
      marginTop: spacing.md,
      paddingVertical: spacing.lg,
      borderRadius: radius.action,
      backgroundColor: c.faint,
      minHeight: 48,
    },
    deleteText: { color: c.expense, fontWeight: '700', fontSize: type.bodySize },
  });
