import { StyleSheet } from 'react-native';
import { radius, spacing, type, type Palette } from '../../theme';

export const makeStyles = (c: Palette) =>
  StyleSheet.create({
    amount: {
      textAlign: 'left',
      color: '#2A223B',
      fontSize: 34,
      fontWeight: '800',
      marginTop: spacing.sm,
    },
    kindSegment: { flexDirection: 'row', marginHorizontal: spacing.xl, padding: spacing.xs, borderRadius: radius.action, backgroundColor: c.primarySoft },
    kindOption: { flex: 1, minHeight: 34, alignItems: 'center', justifyContent: 'center', borderRadius: radius.action },
    kindOptionText: { fontSize: type.metaSize, fontWeight: '700' },
    amountPanel: { marginHorizontal: spacing.xl, marginTop: spacing.md, padding: spacing.lg, borderRadius: 20, minHeight: 88, justifyContent: 'center' },
    amountLabel: { color: c.ink, fontSize: 10, fontWeight: '700' },
    stepHint: {
      textAlign: 'center',
      color: c.muted,
      fontSize: type.metaSize,
      marginBottom: spacing.md,
    },
    noteInput: {
      marginHorizontal: spacing.xl,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: radius.action,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md,
      color: c.ink,
      minHeight: 44,
    },
    divider: { height: 1, backgroundColor: c.border, marginVertical: spacing.md },
    repeatRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginHorizontal: spacing.xl,
      marginTop: spacing.md,
      minHeight: 40,
    },
    repeatLabel: { fontSize: type.bodySize, color: c.ink },
    dateRow: { flexDirection: 'row', gap: spacing.md, marginHorizontal: spacing.xl, marginTop: spacing.md },
    dateControl: { flex: 1, minHeight: 58, justifyContent: 'center', paddingHorizontal: spacing.md, backgroundColor: c.faint, borderRadius: radius.action },
    dateValue: { color: c.ink, fontSize: type.bodySize, fontWeight: '600', marginTop: spacing.xs },
    repeatControl: { flex: 1, minHeight: 58, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: spacing.md, backgroundColor: c.faint, borderRadius: radius.action },
    fieldLabel: {
      marginHorizontal: spacing.xl,
      marginBottom: spacing.sm,
      color: c.muted,
      fontSize: type.metaSize,
      fontWeight: '700',
      textTransform: 'uppercase',
    },
    categorySelect: {
      minHeight: 54,
      marginHorizontal: spacing.xl,
      paddingHorizontal: spacing.lg,
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: radius.action,
      backgroundColor: c.faint,
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.md,
    },
    categorySelectText: { flex: 1, color: c.ink, fontSize: type.bodySize, fontWeight: '600' },
    placeholder: { color: c.muted, fontWeight: '400' },
    chevron: { fontSize: 24, lineHeight: 20, marginTop: -5 },
    submitButton: {
      marginHorizontal: spacing.xl,
      marginTop: spacing.lg,
      minHeight: 50,
      borderRadius: radius.action,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.primary,
    },
    submitButtonDisabled: { opacity: 0.45 },
    submitText: { color: '#FFFFFF', fontSize: type.actionSize, fontWeight: type.actionWeight },
    incomeSubmitText: { color: c.ink },
    deleteButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.sm,
      marginHorizontal: spacing.xl,
      marginTop: spacing.md,
      paddingVertical: spacing.lg,
      borderRadius: radius.action,
      backgroundColor: c.faint,
      minHeight: 48,
    },
    deleteText: { color: c.expense, fontWeight: '700', fontSize: type.bodySize },
  });
