import { StyleSheet } from 'react-native';
import { radius, spacing, type, type Palette } from '../../theme';

export const makeStyles = (c: Palette) =>
  StyleSheet.create({
    content: {
      backgroundColor: c.paper,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingTop: spacing.md,
      paddingBottom: spacing.xl,
      maxHeight: '90%',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: spacing.xl,
      marginBottom: spacing.md,
    },
    title: { fontSize: 18, fontWeight: '800', color: c.ink },
    iconButton: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
    body: { paddingHorizontal: spacing.xl },
    callout: {
      backgroundColor: c.primary,
      borderRadius: radius.action,
      padding: spacing.xl,
      marginBottom: spacing.lg,
    },
    calloutTitle: { color: '#FFFFFF', fontSize: type.actionSize, fontWeight: '800' },
    calloutBody: { color: '#FFFFFF', opacity: 0.9, fontSize: type.metaSize, marginTop: spacing.sm },
    linkCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      minHeight: 68,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md,
      marginBottom: spacing.sm,
      borderRadius: radius.action,
      backgroundColor: c.faint,
    },
    linkCardActive: { borderWidth: 1, borderColor: c.primary },
    linkCopy: { flex: 1, paddingRight: spacing.md },
    linkTitle: { color: c.ink, fontSize: type.bodySize, fontWeight: '700' },
    linkBody: { color: c.muted, fontSize: type.metaSize, marginTop: spacing.xs },
    linkValue: { color: c.primary, fontSize: type.metaSize, fontWeight: '700' },
    chevron: { color: c.primary, fontSize: 24, fontWeight: '600' },
    nameCard: {
      backgroundColor: c.faint,
      borderRadius: radius.action,
      padding: spacing.lg,
      marginBottom: spacing.md,
    },
    pageDescription: { color: c.muted, fontSize: type.bodySize, marginBottom: spacing.lg },
    segmentRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.xs,
      padding: spacing.xs,
      borderRadius: radius.action,
      backgroundColor: c.primarySoft,
    },
    segment: {
      flex: 1,
      minHeight: 40,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.sm,
      borderRadius: radius.action,
    },
    segmentActive: { backgroundColor: c.primary },
    primaryButton: {
      minHeight: 48,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.xl,
      borderRadius: radius.action,
      backgroundColor: c.primary,
      marginTop: spacing.md,
    },
    primaryButtonText: { color: c.onAction, fontSize: type.bodySize, fontWeight: '700' },
    secondaryButton: {
      minHeight: 48,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.xl,
      borderRadius: radius.action,
      backgroundColor: c.primarySoft,
      marginTop: spacing.md,
    },
    secondaryButtonText: { color: c.ink, fontSize: type.bodySize, fontWeight: '700' },
    section: { fontSize: type.metaSize, color: c.muted, fontWeight: '700', marginTop: spacing.lg, marginBottom: spacing.md, textTransform: 'uppercase' },
    chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
    chip: {
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.xl,
      borderRadius: radius.action,
      backgroundColor: c.faint,
      minHeight: 40,
      justifyContent: 'center',
    },
    chipActive: { backgroundColor: c.primary },
    chipText: { fontSize: type.bodySize, color: c.ink },
    chipTextActive: { color: '#FFFFFF' },
    avatarRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, marginTop: spacing.lg },
    avatarCell: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: c.faint,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 2,
      borderColor: 'transparent',
    },
    avatarCellActive: { borderColor: c.ink },
    input: {
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: radius.action,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md,
      color: c.ink,
      minHeight: 44,
    },
    actionButton: {
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.xl,
      borderRadius: radius.action,
      backgroundColor: c.faint,
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionButtonText: { color: c.ink, fontWeight: '600', fontSize: type.bodySize },
    inputDisabled: { opacity: 0.6 },
    importConfirm: { marginTop: spacing.md },
    importInput: {
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: radius.action,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.md,
      color: c.ink,
      minHeight: 96,
      textAlignVertical: 'top',
      marginTop: spacing.md,
    },
    toggleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      minHeight: 60,
      paddingHorizontal: spacing.lg,
      marginTop: spacing.md,
      borderRadius: radius.action,
      backgroundColor: c.faint,
    },
    toggleLabel: { fontSize: type.bodySize, color: c.ink },
  });
